/***********************************************************************/
/*                                                                     */
/*  FILE        :enn4.c                                                */
/*  DATE        :Sat, Feb 12, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  

#include "timerA.h"
#include "led.h"
void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void main(void)
{
	//initLED();
	initTIimerA();
	
	while(1){
	
	
	}

}

#ifdef __cplusplus
void abort(void)
{

}
#endif
