/***********************************************************************/
/*                                                                     */
/*  FILE        :QQ.c                                                  */
/*  DATE        :Fri, Feb 04, 2022                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/3694F                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.16).    */
/*                                                                     */
/***********************************************************************/
                  


void main(void);
#ifdef __cplusplus
#include "machine.h"
#include "iodefine.h"
#include "led.h"
#include "intsw.h"
extern "C" {
void abort(void);
}
#endif

void main(void)
{
   
    //initLED();
	initSWint();
	
	while(1){
		
		}
}


#ifdef __cplusplus
void abort(void)
{

}
#endif
